FROM nginx

WORKDIR /mini_server

COPY /server/mini_server.c /mini_server/
COPY /server/start_mini_server.sh /mini_server/
COPY /server/nginx/nginx.conf /etc/nginx/nginx.conf

RUN apt-get update; \
    apt-get install -y gcc\
    spawn-fcgi \
    libfcgi-dev

CMD ["sh", "./start_mini_server.sh"]
