version: "3.3"

services:
  mini_server:
    build:
      context: .
      dockerfile: ./part_5/Dockerfile_5
    container_name: mini_server
    tty: true
  part6:
    image: nginx
    container_name: proxy_part6
    ports:
      - 80:8080
    depends_on:
      - mini_server
    volumes:
      - ./part_6/nginx.conf:/etc/nginx/nginx.conf
